/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterBoardSM;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Jerry
 */
public class BienvenidoMaestro extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenido
     */
    public BienvenidoMaestro() {
        initComponents();
       panelComponentes.setBackground(Color.WHITE);
        setLocationRelativeTo(null);
        setTitle("Inicio");
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
       
         PanelImagenBienvenido p = new PanelImagenBienvenido();
         p.setBorder(new EmptyBorder(5, 5, 5, 5));
         p.setLayout(new BorderLayout(0, 0));
         panelLogo.add(p);
       
   // panelLogo.setBackground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelComponentes = new javax.swing.JPanel();
        panelLogo = new javax.swing.JPanel();
        barraMenu = new javax.swing.JMenuBar();
        menuGrupos = new javax.swing.JMenu();
        subMenuMisGrupos = new javax.swing.JMenuItem();
        subMenuNuevoGrupo = new javax.swing.JMenuItem();
        menuTareas = new javax.swing.JMenu();
        subMenuNuevaTarea = new javax.swing.JMenuItem();
        menuAvisos = new javax.swing.JMenu();
        subMenuNuevoAviso = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        subMenuNuevoReporte = new javax.swing.JMenuItem();
        menuEventos = new javax.swing.JMenu();
        subMenuNuevoEvento = new javax.swing.JMenuItem();
        menuCalificaciones = new javax.swing.JMenu();
        subMenuReportarCalificaciones = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        subMenuCerrarSesion = new javax.swing.JMenuItem();
        subMenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelComponentes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelComponentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 630, 180));

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        getContentPane().add(panelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 180));

        barraMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuGrupos.setText("Grupos");
        menuGrupos.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        subMenuMisGrupos.setText("Mis grupos");
        subMenuMisGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuMisGruposActionPerformed(evt);
            }
        });
        menuGrupos.add(subMenuMisGrupos);

        subMenuNuevoGrupo.setText("Nuevo grupo");
        subMenuNuevoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuNuevoGrupoActionPerformed(evt);
            }
        });
        menuGrupos.add(subMenuNuevoGrupo);

        barraMenu.add(menuGrupos);

        menuTareas.setText("Tareas");
        menuTareas.setFocusable(false);
        menuTareas.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        subMenuNuevaTarea.setText("Nueva tarea");
        subMenuNuevaTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuNuevaTareaActionPerformed(evt);
            }
        });
        menuTareas.add(subMenuNuevaTarea);

        barraMenu.add(menuTareas);

        menuAvisos.setText("Avisos");
        menuAvisos.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        subMenuNuevoAviso.setText("Nuevo aviso");
        subMenuNuevoAviso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuNuevoAvisoActionPerformed(evt);
            }
        });
        menuAvisos.add(subMenuNuevoAviso);

        barraMenu.add(menuAvisos);

        menuReportes.setText("Reportes");
        menuReportes.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        subMenuNuevoReporte.setText("Nuevo reporte");
        subMenuNuevoReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuNuevoReporteActionPerformed(evt);
            }
        });
        menuReportes.add(subMenuNuevoReporte);

        barraMenu.add(menuReportes);

        menuEventos.setText("Eventos");
        menuEventos.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        subMenuNuevoEvento.setText("Nuevo evento");
        subMenuNuevoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuNuevoEventoActionPerformed(evt);
            }
        });
        menuEventos.add(subMenuNuevoEvento);

        barraMenu.add(menuEventos);

        menuCalificaciones.setText("Calificaciones");
        menuCalificaciones.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        subMenuReportarCalificaciones.setText("Reportar calificaciones");
        subMenuReportarCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuReportarCalificacionesActionPerformed(evt);
            }
        });
        menuCalificaciones.add(subMenuReportarCalificaciones);

        barraMenu.add(menuCalificaciones);

        menuSalir.setText("Salir");
        menuSalir.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });

        subMenuCerrarSesion.setText("Cerrar sesion");
        subMenuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCerrarSesionActionPerformed(evt);
            }
        });
        menuSalir.add(subMenuCerrarSesion);

        subMenuSalir.setText("Salir");
        subMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuSalirActionPerformed(evt);
            }
        });
        menuSalir.add(subMenuSalir);

        barraMenu.add(menuSalir);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //^^^^^^^^EVENTOS DEL MENU////EVENTOS DEL MENU ///EVENTOS DEL MENU /// EVENTOS DEL MENU //////^^^^^^^^^^
    
//EVENTOS DEL SUBMENU NUEVA TAREA EN EL MENU DE TAREAS     
    private void subMenuNuevaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuNuevaTareaActionPerformed
       if(evt.getSource()==subMenuNuevaTarea){
           NuevaTarea nuevaTarea = new NuevaTarea(); //SE CREA OBJETO TIPO MIS GRUPOS PARA LLAMAR AL FRAME
           nuevaTarea.setVisible(true); //SE LLAMA AL FRAME
           //this.dispose(); //CIERRA LA VENTANA 
        }
    }//GEN-LAST:event_subMenuNuevaTareaActionPerformed

//EVENTOS DEL SUBMENU MIS GRUPOS EN EL MENU DE GRUPOS 
    private void subMenuMisGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuMisGruposActionPerformed
        if(evt.getSource()==subMenuMisGrupos){
           MisGrupos misGrupos = new MisGrupos(); //SE CREA OBJETO TIPO MIS GRUPOS PARA LLAMAR AL FRAME
           misGrupos.setVisible(true); //SE LLAMA AL FRAME
           //this.dispose(); //CIERRA LA VENTANA 
        }
    }//GEN-LAST:event_subMenuMisGruposActionPerformed
//EVENTOS DEL SUBMENU MIS GRUPOS EN EL MENU DE GRUPOS
    private void subMenuNuevoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuNuevoGrupoActionPerformed
        if(evt.getSource()==subMenuNuevoGrupo){
           NuevoGrupo nuevoGrupo = new NuevoGrupo(); //SE CREA OBJETO TIPO MIS GRUPOS PARA LLAMAR AL FRAME
           nuevoGrupo.setVisible(true); //SE LLAMA AL FRAME
           //this.dispose(); //CIERRA LA VENTANA 
        }
    }//GEN-LAST:event_subMenuNuevoGrupoActionPerformed
////EVENTOS DEL SUBMENU NUEVO AVISO EN EL MENU DE AVISOS
    private void subMenuNuevoAvisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuNuevoAvisoActionPerformed
        if(evt.getSource()==subMenuNuevoAviso){
           NuevoAviso nuevoAviso = new NuevoAviso(); //SE CREA OBJETO TIPO MIS GRUPOS PARA LLAMAR AL FRAME
           nuevoAviso.setVisible(true); //SE LLAMA AL FRAME
           //this.dispose(); //CIERRA LA VENTANA 
        }
    }//GEN-LAST:event_subMenuNuevoAvisoActionPerformed
////EVENTOS DEL SUBMENU NUEVO REPORTE EN EL MENU DE REPORTES
    private void subMenuNuevoReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuNuevoReporteActionPerformed
        if(evt.getSource()==subMenuNuevoReporte){
           NuevoReporte nuevoReporte = new NuevoReporte(); //SE CREA OBJETO TIPO MIS GRUPOS PARA LLAMAR AL FRAME
           nuevoReporte.setVisible(true); //SE LLAMA AL FRAME
           //this.dispose(); //CIERRA LA VENTANA 
        }
    }//GEN-LAST:event_subMenuNuevoReporteActionPerformed
////EVENTOS DEL SUBMENU NUEVO EVENTO EN EL MENU DE EVENTOS
    private void subMenuNuevoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuNuevoEventoActionPerformed
         if(evt.getSource()==subMenuNuevoEvento){
           NuevoEvento nuevoEvento = new NuevoEvento(); //SE CREA OBJETO TIPO MIS GRUPOS PARA LLAMAR AL FRAME
           nuevoEvento.setVisible(true); //SE LLAMA AL FRAME
           //this.dispose(); //CIERRA LA VENTANA 
        }
    }//GEN-LAST:event_subMenuNuevoEventoActionPerformed
////EVENTOS DEL SUBMENU REPORTAR CALIFICACIONES EN EL MENU DE CALIFICACIONES
    private void subMenuReportarCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuReportarCalificacionesActionPerformed
        if(evt.getSource()==subMenuReportarCalificaciones){
           ReportarCalificaciones reportarCalificaciones = new ReportarCalificaciones(); //SE CREA OBJETO TIPO MIS GRUPOS PARA LLAMAR AL FRAME
           reportarCalificaciones.setVisible(true); //SE LLAMA AL FRAME
           //this.dispose(); //CIERRA LA VENTANA 
        }
    }//GEN-LAST:event_subMenuReportarCalificacionesActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        if(evt.getSource()==menuSalir){
           Login login = new Login(); //SE CREA OBJETO TIPO MIS GRUPOS PARA LLAMAR AL FRAME
           login.setVisible(true); //SE LLAMA AL FRAME
           this.dispose(); //CIERRA LA VENTANA 
        }
    }//GEN-LAST:event_menuSalirActionPerformed

    private void subMenuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCerrarSesionActionPerformed
       if(evt.getSource()==subMenuCerrarSesion){
           Login login = new Login(); //SE CREA OBJETO TIPO MIS GRUPOS PARA LLAMAR AL FRAME
           login.setVisible(true); //SE LLAMA AL FRAME
           this.dispose(); //CIERRA LA VENTANA 
        }
    }//GEN-LAST:event_subMenuCerrarSesionActionPerformed

    private void subMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuSalirActionPerformed
       if(evt.getSource()==subMenuSalir){
           System.exit(0);
        }
    }//GEN-LAST:event_subMenuSalirActionPerformed

    // END //^^^^^^^^EVENTOS DEL MENU////EVENTOS DEL MENU ///EVENTOS DEL MENU /// EVENTOS DEL MENU //////^^^^^^^^^^
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BienvenidoMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BienvenidoMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BienvenidoMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BienvenidoMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BienvenidoMaestro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu menuAvisos;
    private javax.swing.JMenu menuCalificaciones;
    private javax.swing.JMenu menuEventos;
    private javax.swing.JMenu menuGrupos;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenu menuTareas;
    private javax.swing.JPanel panelComponentes;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JMenuItem subMenuCerrarSesion;
    private javax.swing.JMenuItem subMenuMisGrupos;
    private javax.swing.JMenuItem subMenuNuevaTarea;
    private javax.swing.JMenuItem subMenuNuevoAviso;
    private javax.swing.JMenuItem subMenuNuevoEvento;
    private javax.swing.JMenuItem subMenuNuevoGrupo;
    private javax.swing.JMenuItem subMenuNuevoReporte;
    private javax.swing.JMenuItem subMenuReportarCalificaciones;
    private javax.swing.JMenuItem subMenuSalir;
    // End of variables declaration//GEN-END:variables
}
