/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterBoardSM;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
//
/**
 *
 * @author Jerry
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN1
     */
    public Login() {
        initComponents();
       
        panelComponentes.setBackground(Color.white);
        
        setLocationRelativeTo(null);
        setTitle("Iniciar sesion");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        
        PanelImagen p = new PanelImagen();
         p.setBorder(new EmptyBorder(5, 5, 5, 5));
         p.setLayout(new BorderLayout(0, 0));
         panelLogo.add(p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelComponentes = new javax.swing.JPanel();
        etiquetaContraseña = new javax.swing.JLabel();
        boxUsuario = new javax.swing.JTextField();
        etiquetaUsuario = new javax.swing.JLabel();
        boxContraseña = new javax.swing.JPasswordField();
        botonEntrar = new javax.swing.JButton();
        botonRegistrarse = new javax.swing.JButton();
        panelLogo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelComponentes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaContraseña.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        etiquetaContraseña.setText("Contraseña");
        panelComponentes.add(etiquetaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));
        panelComponentes.add(boxUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 250, 30));

        etiquetaUsuario.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        etiquetaUsuario.setText("Usuario");
        panelComponentes.add(etiquetaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));
        panelComponentes.add(boxContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 250, 30));

        botonEntrar.setFont(new java.awt.Font("MV Boli", 1, 20)); // NOI18N
        botonEntrar.setText("Entrar");
        botonEntrar.setVerifyInputWhenFocusTarget(false);
        botonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrarActionPerformed(evt);
            }
        });
        panelComponentes.add(botonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, 40));
        botonEntrar.getAccessibleContext().setAccessibleDescription("");

        botonRegistrarse.setFont(new java.awt.Font("MV Boli", 1, 20)); // NOI18N
        botonRegistrarse.setText("Registrarse");
        botonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarseActionPerformed(evt);
            }
        });
        panelComponentes.add(botonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 150, 40));

        getContentPane().add(panelComponentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 196, 360, 260));

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        getContentPane().add(panelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//ACTION EVENT DEL BOTON RESITRARSE
    private void botonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarseActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==botonRegistrarse){
           Registro registro = new Registro(); 
           registro.setVisible(true); //ABRE EL FRAME DE REGISTRO
           //this.dispose(); //CIERRA LA VENTANA 
        }
    }//GEN-LAST:event_botonRegistrarseActionPerformed

    private void botonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrarActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==botonEntrar){
            if(boxUsuario.getText().equalsIgnoreCase("M")){
                JOptionPane.showMessageDialog(null,"Bienvenido MAESTRO"); 
                BienvenidoMaestro bienv = new BienvenidoMaestro();
                 bienv.setVisible(true);
                 this.dispose();
            }
             if(boxUsuario.getText().equalsIgnoreCase("P")){
                 JOptionPane.showMessageDialog(null,"BIENVENIDO PADRE DEL ALUMNO");
                 BienvenidoPadre bienv = new BienvenidoPadre();
                 bienv.setVisible(true);
                 this.dispose();
            }
              
           
        }
    }//GEN-LAST:event_botonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEntrar;
    private javax.swing.JButton botonRegistrarse;
    private javax.swing.JPasswordField boxContraseña;
    private javax.swing.JTextField boxUsuario;
    private javax.swing.JLabel etiquetaContraseña;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JPanel panelComponentes;
    private javax.swing.JPanel panelLogo;
    // End of variables declaration//GEN-END:variables
}
