/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterBoardSM;


import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Jerry
 */
public class ModificarGrupo extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenido
     */
    public ModificarGrupo() {
        initComponents();
       panelComponentes.setBackground(Color.WHITE);
        setLocationRelativeTo(null);
        setTitle("Modificar Grupo");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        
       
              
       
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogoBienv = new javax.swing.JPanel();
        panelComponentes = new javax.swing.JPanel();
        comboBoxGrupo = new javax.swing.JComboBox<>();
        etiquetaGrupo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlumnos = new javax.swing.JTable();
        botonGuardar = new javax.swing.JButton();
        botonBuscarGrupo = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogoBienv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelComponentes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboBoxGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G" }));
        panelComponentes.add(comboBoxGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 220, 30));

        etiquetaGrupo.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        etiquetaGrupo.setText("Grupo:");
        panelComponentes.add(etiquetaGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 70, 30));

        tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null},
                {"2", null},
                {"3", null},
                {"4", null},
                {"5", null},
                {"6", null},
                {"7", null},
                {"8", null},
                {"9", null},
                {"10", null},
                {"11", ""},
                {"12", null},
                {"13", null},
                {"14", null},
                {"15", null},
                {"16", null},
                {"17", null},
                {"18", null},
                {"19", null},
                {"20", null},
                {"21", null},
                {"22", null},
                {"23", null},
                {"24", null},
                {"25", null}
            },
            new String [] {
                "#", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaAlumnos);
        if (tablaAlumnos.getColumnModel().getColumnCount() > 0) {
            tablaAlumnos.getColumnModel().getColumn(0).setResizable(false);
            tablaAlumnos.getColumnModel().getColumn(0).setPreferredWidth(25);
            tablaAlumnos.getColumnModel().getColumn(1).setResizable(false);
            tablaAlumnos.getColumnModel().getColumn(1).setPreferredWidth(450);
        }

        panelComponentes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 470, -1));

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        panelComponentes.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 150, 40));

        botonBuscarGrupo.setText("Buscar");
        botonBuscarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarGrupoActionPerformed(evt);
            }
        });
        panelComponentes.add(botonBuscarGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 90, 30));

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panelComponentes.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 160, 40));

        panelLogoBienv.add(panelComponentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 630));

        getContentPane().add(panelLogoBienv, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //ACTION PERFORMED DEL BOTON BUSCAR 
    private void botonBuscarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarGrupoActionPerformed
        if(evt.getSource()==botonBuscarGrupo){
           JOptionPane.showMessageDialog(null, "SE HA PRESIONADO BUSCAR GRUPO");
        }
    }//GEN-LAST:event_botonBuscarGrupoActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        if(evt.getSource()==botonGuardar){
           JOptionPane.showMessageDialog(null, "GRUPO GUARDADO CORRECTAMENTE");
            this.dispose(); //CIERRA LA VENTANA 
        
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
         if(evt.getSource()==botonCancelar){
         //MisGrupos misGrupos = new MisGrupos(); //SE CREA OBJETO TIPO MIS GRUPOS PARA LLAMAR AL FRAME
           //misGrupos.setVisible(true); //SE LLAMA AL FRAME
           JOptionPane.showMessageDialog(null, "SE HA CANCELADO LA MODIFICACION");
            this.dispose(); //CIERRA LA VENTANA 
            
        
        }
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarGrupo;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JComboBox<String> comboBoxGrupo;
    private javax.swing.JLabel etiquetaGrupo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelComponentes;
    private javax.swing.JPanel panelLogoBienv;
    private javax.swing.JTable tablaAlumnos;
    // End of variables declaration//GEN-END:variables
}
