/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterBoardSM;


import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Jerry
 */
public class NuevoReporte extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenido
     */
    public NuevoReporte() {
        initComponents();
       panelComponentes.setBackground(Color.WHITE);
        setLocationRelativeTo(null);
        setTitle("Nuevo reporte");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
       
       // Para que se partan automáticamente las líneas al llegar al final 
        areaTextoReporte.setLineWrap(true); 

        // Para que el partido se haga respetando las palabras. Sólo se parte la 
        // línea en los espacios entre palabras. 
        areaTextoReporte.setWrapStyleWord(true); 
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelComponentes = new javax.swing.JPanel();
        etiquetaTipoReporte = new javax.swing.JLabel();
        comboBoxGrupos = new javax.swing.JComboBox<>();
        etiquetaDescripcionReporte = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTextoReporte = new javax.swing.JTextArea();
        botonCancelar = new javax.swing.JButton();
        botonEnviar = new javax.swing.JButton();
        etiquetaFechaDeReporte = new javax.swing.JLabel();
        comboBoxDia = new javax.swing.JComboBox<>();
        comboBoxMes = new javax.swing.JComboBox<>();
        comboBoxAnio = new javax.swing.JComboBox<>();
        etiquetaGrupoDelAlumno = new javax.swing.JLabel();
        comboBoxNumLista = new javax.swing.JComboBox<>();
        etiquetaNumeroLista = new javax.swing.JLabel();
        comboBoxTipoReporte = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelComponentes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaTipoReporte.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        etiquetaTipoReporte.setText("Tipo de reporte:");
        panelComponentes.add(etiquetaTipoReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, 30));

        comboBoxGrupos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelComponentes.add(comboBoxGrupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 200, 30));

        etiquetaDescripcionReporte.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        etiquetaDescripcionReporte.setText("Descripcion del reporte:");
        panelComponentes.add(etiquetaDescripcionReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 30));

        areaTextoReporte.setColumns(20);
        areaTextoReporte.setRows(5);
        jScrollPane1.setViewportView(areaTextoReporte);

        panelComponentes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 450, 200));

        botonCancelar.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panelComponentes.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        botonEnviar.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        botonEnviar.setText("Enviar");
        botonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarActionPerformed(evt);
            }
        });
        panelComponentes.add(botonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 110, -1));

        etiquetaFechaDeReporte.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        etiquetaFechaDeReporte.setText("Fecha:");
        panelComponentes.add(etiquetaFechaDeReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, 20));

        comboBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        panelComponentes.add(comboBoxDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        comboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octube", "Noviembre", "Diciembre" }));
        panelComponentes.add(comboBoxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        comboBoxAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2015", "2016", "2017", "2018", "2019", "2020" }));
        panelComponentes.add(comboBoxAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        etiquetaGrupoDelAlumno.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        etiquetaGrupoDelAlumno.setText("Grupo del alumno:");
        panelComponentes.add(etiquetaGrupoDelAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 30));

        comboBoxNumLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));
        panelComponentes.add(comboBoxNumLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, 30));

        etiquetaNumeroLista.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        etiquetaNumeroLista.setText("Numero de lista:");
        panelComponentes.add(etiquetaNumeroLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 30));

        comboBoxTipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Urgente" }));
        panelComponentes.add(comboBoxTipoReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 120, 30));

        getContentPane().add(panelComponentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
         if(evt.getSource()==botonCancelar){
         this.dispose(); //CIERRA LA VENTANA 
        
        }
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
         if(evt.getSource()==botonEnviar){
          JOptionPane.showMessageDialog(null,"Reporte enviado exitosamente");
           this.dispose(); //CIERRA LA VENTANA 
        
        }
    }//GEN-LAST:event_botonEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
     
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoReporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTextoReporte;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEnviar;
    private javax.swing.JComboBox<String> comboBoxAnio;
    private javax.swing.JComboBox<String> comboBoxDia;
    private javax.swing.JComboBox<String> comboBoxGrupos;
    private javax.swing.JComboBox<String> comboBoxMes;
    private javax.swing.JComboBox<String> comboBoxNumLista;
    private javax.swing.JComboBox<String> comboBoxTipoReporte;
    private javax.swing.JLabel etiquetaDescripcionReporte;
    private javax.swing.JLabel etiquetaFechaDeReporte;
    private javax.swing.JLabel etiquetaGrupoDelAlumno;
    private javax.swing.JLabel etiquetaNumeroLista;
    private javax.swing.JLabel etiquetaTipoReporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelComponentes;
    // End of variables declaration//GEN-END:variables
}
