/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterBoardSM;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Jerry
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN1
     */
    public Registro() {
        initComponents();
       
        panelComponentes.setBackground(Color.white);
        
        setLocationRelativeTo(null);
        setTitle("Registrarse");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        
        PanelImagenRegistro p = new PanelImagenRegistro();
    p.setBorder(new EmptyBorder(5, 5, 5, 5));
    p.setLayout(new BorderLayout(0, 0));
    panelLogo.add(p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelComponentes = new javax.swing.JPanel();
        etiquetaContraseña = new javax.swing.JLabel();
        boxDireccion = new javax.swing.JTextField();
        etiquetaNombreUsuario = new javax.swing.JLabel();
        boxContraseña = new javax.swing.JPasswordField();
        botonCancelar = new javax.swing.JButton();
        botonRegistrarse = new javax.swing.JButton();
        boxNombre = new javax.swing.JTextField();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaApellidoPaterno = new javax.swing.JLabel();
        boxApellidoPaterno = new javax.swing.JTextField();
        etiquetaApellidoMaterno = new javax.swing.JLabel();
        boxApellidoMaterno = new javax.swing.JTextField();
        etiquetaCorreoElectronico = new javax.swing.JLabel();
        etiquetaTelefono = new javax.swing.JLabel();
        etiquetaDireccion = new javax.swing.JLabel();
        etiquetaTipoUsuario = new javax.swing.JLabel();
        comboBoxTipoUsuario = new javax.swing.JComboBox<>();
        etiquetaGrupoAlumno = new javax.swing.JLabel();
        comboBoxGrupoAlumno = new javax.swing.JComboBox<>();
        boxNombreUsuario = new javax.swing.JTextField();
        boxCorreoElectronico = new javax.swing.JTextField();
        boxTelefono = new javax.swing.JTextField();
        boxConfirmarContraseña = new javax.swing.JPasswordField();
        etiquetaConfirmarContraseña = new javax.swing.JLabel();
        panelLogo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelComponentes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaContraseña.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        etiquetaContraseña.setText("Contraseña:");
        panelComponentes.add(etiquetaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));
        panelComponentes.add(boxDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 170, 30));

        etiquetaNombreUsuario.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        etiquetaNombreUsuario.setText("Nombre de usuario:");
        panelComponentes.add(etiquetaNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        panelComponentes.add(boxContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 170, 30));

        botonCancelar.setFont(new java.awt.Font("MV Boli", 1, 20)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.setVerifyInputWhenFocusTarget(false);
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panelComponentes.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 120, 40));
        botonCancelar.getAccessibleContext().setAccessibleDescription("");

        botonRegistrarse.setFont(new java.awt.Font("MV Boli", 1, 20)); // NOI18N
        botonRegistrarse.setText("Registrarse");
        botonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarseActionPerformed(evt);
            }
        });
        panelComponentes.add(botonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 150, 40));
        panelComponentes.add(boxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 170, 30));

        etiquetaNombre.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        etiquetaNombre.setText("Nombre:");
        panelComponentes.add(etiquetaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        etiquetaApellidoPaterno.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        etiquetaApellidoPaterno.setText("Apellido Paterno:");
        panelComponentes.add(etiquetaApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));
        panelComponentes.add(boxApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 170, 30));

        etiquetaApellidoMaterno.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        etiquetaApellidoMaterno.setText("Apellido Materno:");
        panelComponentes.add(etiquetaApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));
        panelComponentes.add(boxApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 170, 30));

        etiquetaCorreoElectronico.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        etiquetaCorreoElectronico.setText("Correo electronico:");
        panelComponentes.add(etiquetaCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        etiquetaTelefono.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        etiquetaTelefono.setText("Telefono:");
        panelComponentes.add(etiquetaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        etiquetaDireccion.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        etiquetaDireccion.setText("Direccion:");
        panelComponentes.add(etiquetaDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        etiquetaTipoUsuario.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        etiquetaTipoUsuario.setText("Tipo de usuario:");
        panelComponentes.add(etiquetaTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        comboBoxTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Padre de alumno", "Profesor" }));
        panelComponentes.add(comboBoxTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 170, 30));

        etiquetaGrupoAlumno.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        etiquetaGrupoAlumno.setText("Grupo del alumno:");
        panelComponentes.add(etiquetaGrupoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        comboBoxGrupoAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "Soy Profesor" }));
        panelComponentes.add(comboBoxGrupoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 170, 30));
        panelComponentes.add(boxNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 170, 30));
        panelComponentes.add(boxCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 170, 30));
        panelComponentes.add(boxTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 170, 30));
        panelComponentes.add(boxConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 170, 30));

        etiquetaConfirmarContraseña.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        etiquetaConfirmarContraseña.setText("Confirmar contraseña:");
        panelComponentes.add(etiquetaConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        getContentPane().add(panelComponentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 480, 520));

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        getContentPane().add(panelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarseActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==botonRegistrarse){
           JOptionPane.showMessageDialog(null,"SE HA REGISTRADO EXITOSAMENTE");
           Login login = new Login();
           login.setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_botonRegistrarseActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==botonCancelar){
           Login login = new Login();
           login.setVisible(true);
           this.dispose();
           
        }
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegistrarse;
    private javax.swing.JTextField boxApellidoMaterno;
    private javax.swing.JTextField boxApellidoPaterno;
    private javax.swing.JPasswordField boxConfirmarContraseña;
    private javax.swing.JPasswordField boxContraseña;
    private javax.swing.JTextField boxCorreoElectronico;
    private javax.swing.JTextField boxDireccion;
    private javax.swing.JTextField boxNombre;
    private javax.swing.JTextField boxNombreUsuario;
    private javax.swing.JTextField boxTelefono;
    private javax.swing.JComboBox<String> comboBoxGrupoAlumno;
    private javax.swing.JComboBox<String> comboBoxTipoUsuario;
    private javax.swing.JLabel etiquetaApellidoMaterno;
    private javax.swing.JLabel etiquetaApellidoPaterno;
    private javax.swing.JLabel etiquetaConfirmarContraseña;
    private javax.swing.JLabel etiquetaContraseña;
    private javax.swing.JLabel etiquetaCorreoElectronico;
    private javax.swing.JLabel etiquetaDireccion;
    private javax.swing.JLabel etiquetaGrupoAlumno;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaNombreUsuario;
    private javax.swing.JLabel etiquetaTelefono;
    private javax.swing.JLabel etiquetaTipoUsuario;
    private javax.swing.JPanel panelComponentes;
    private javax.swing.JPanel panelLogo;
    // End of variables declaration//GEN-END:variables
}
